### PR TITLE
Escape keywords

### LINKED ISSUE #265: Autogenerated bindings use unescaped keyword
When I try to use certain APIs in ``windows::globalization`` (I was trying to use the phone number formatting API), I get a compiler error like this:

```
   Compiling bindings v0.1.0 (D:\Code\Rust\winrtery\bindings)
 Documenting bindings v0.1.0 (D:\Code\Rust\winrtery\bindings)
error: expected identifier, found reserved keyword `try`
     --> D:\Code\Rust\winrtery\bindings\target\debug\build\bindings-257f5038b133d91b\out/winrt.rs:19060:20
      |
19060 |             pub fn try() -> ::winrt::Result<::winrt::HString> {
      |                    ^^^ expected identifier, found reserved keyword
      |
help: you can escape reserved keywords to use them as identifiers
      |
19060 |             pub fn r#try() -> ::winrt::Result<::winrt::HString> {
      |                    ^^^^^

error: expected identifier, found reserved keyword `try`
     --> D:\Code\Rust\winrtery\bindings\target\debug\build\bindings-257f5038b133d91b\out/winrt.rs:19061:74
      |
19061 |                 ::winrt::factory::<Self, ICurrencyIdentifiersStatics>()?.try()
      |                                                                          ^^^ expected identifier, found reserved keyword
      |
help: you can escape reserved keywords to use them as identifiers
      |
19061 |                 ::winrt::factory::<Self, ICurrencyIdentifiersStatics>()?.r#try()
      |                                                                          ^^^^^

error: expected identifier, found reserved keyword `try`
     --> D:\Code\Rust\winrtery\bindings\target\debug\build\bindings-257f5038b133d91b\out/winrt.rs:23787:20
      |
23787 |             pub fn try(&self) -> ::winrt::Result<::winrt::HString> {
      |                    ^^^ expected identifier, found reserved keyword
      |
help: you can escape reserved keywords to use them as identifiers
      |
23787 |             pub fn r#try(&self) -> ::winrt::Result<::winrt::HString> {
      |                    ^^^^^

error: expected identifier, found reserved keyword `try`
     --> D:\Code\Rust\winrtery\bindings\target\debug\build\bindings-257f5038b133d91b\out/winrt.rs:23792:36
      |
23792 |                     (this.vtable().try)(
      |                                    ^^^ expected identifier, found reserved keyword
      |
help: you can escape reserved keywords to use them as identifiers
      |
23792 |                     (this.vtable().r#try)(
      |                                    ^^^^^

error: expected identifier, found reserved keyword `try`
     --> D:\Code\Rust\winrtery\bindings\target\debug\build\bindings-257f5038b133d91b\out/winrt.rs:24613:17
      |
24613 |             pub try: unsafe extern "system" fn(
      |                 ^^^ expected identifier, found reserved keyword
      |
help: you can escape reserved keywords to use them as identifiers
      |
24613 |             pub r#try: unsafe extern "system" fn(
      |                 ^^^^^

error: Compilation failed, aborting rustdoc

error: aborting due to 6 previous errors

error: Could not document `bindings`.

Caused by:
  process didn't exit successfully: `rustdoc --edition=2018 --crate-type lib --crate-name bindings src\lib.rs -o D:\Code\Rust\winrtery\bindings\target\doc --error-format=json --json=diagnostic-rendered-ansi -L dependency=D:\Code\Rust\winrtery\bindings\target\debug\deps --extern winrt=D:\Code\Rust\winrtery\bindings\target\debug\deps\libwinrt-dccf3f1978137b44.rmeta` (exit code: 1)
```

It seems that it's trying to use ``try`` as the name of a function, but in order to do that it has to be escaped as ``r#try``.

### PR DESCRIPTION
**Pull request by rylev**
Fixes #265

### CODE REVIEW

File: crates/gen/src/lib.rs [hunk 1]
```diff
@@ -25,9 +25,16 @@ fn format_ident(name: &str) -> proc_macro2::Ident {
     if name == "Self" {
         quote::format_ident!("{}_", name)
     } else {
-        match syn::parse_str::<proc_macro2::Ident>(name) {
-            Ok(i) => i,
-            Err(_) => quote::format_ident!("r#{}", name),
+        // keywords list based on https://doc.rust-lang.org/reference/keywords.html
+        match name {
```
Comment (kennykerr) [inline crates/gen/src/lib.rs:29]: I'm just not sure whether this is worthwhile over just escaping all names. If its about code completion, we should fix rust-analyzer to demangle the name. At the very least we should check what if any impact this has on code gen time.

Comment (rylev) [reply crates/gen/src/lib.rs:29]: This list is stagnate so it's not a maintenance burden really. We should check performance though. This is actually what we were doing before just now checking for a few additional keywords.

Comment (kennykerr) [reply crates/gen/src/lib.rs:29]: Tested this and it doesn't appear to make a measurable difference. 👍
